name = "CFSjul"
uuid = "e99f7174-7054-485a-9879-8c732ee2472c"
version = "0.1.0"
authors = ["Ivan Perez Avellaneda <iperezave@gmail.com>"]

[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
DocumenterTools = "35a29f4d-8980-5a13-9543-d66fff28ecb8"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"

[compat]
Documenter = "1.16.1"
DocumenterTools = "0.1.21"
LinearAlgebra = "1.12.0"
Symbolics = "7.4.1"
